In [5]:
!pip3 install wget

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting wget
  Downloading wget-3.2.zip (10 kB)
Building wheels for collected packages: wget
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9675 sha256=73634f538fcbf8a85f3c21fc2f7ab61df6e6ddb32b9891db51c6f6268bc7ddc9
  Stored in directory: /root/.cache/pip/wheels/a1/b6/7c/0e63e34eb06634181c63adacca38b79ff8f35c37e3c13e3c02
Successfully built wget
Installing collected packages: wget
Successfully installed wget-3.2

In [6]:
import numpy as np
import pandas as pd
import wget

## 1. Introduction to Machine Learning

**1-What's the version of NumPy that you installed?**

In [2]:
np.__version__

'1.21.6'

In [8]:
url = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'
filename = wget.download(url)
data = pd.read_csv(filename)
data.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

**2-How many records are in the dataset?**

In [11]:
print(len(data))
print(data.shape[0])

11914
11914

**3-Who are the most frequent car manufacturers (top-3) according to the dataset?**

In [14]:
pd.DataFrame(data['Make'].value_counts()).T

,Chevrolet,Ford,Volkswagen,Toyota,Dodge,Nissan,GMC,Honda,Mazda,Cadillac,...,Rolls-Royce,Lotus,Tesla,HUMMER,Maybach,Alfa Romeo,McLaren,Spyker,Genesis,Bugatti
Make,1123,881,809,746,626,558,515,449,423,397,...,31,29,18,17,16,5,5,3,3,3

In [17]:
# the top 3 -> Chevrolet , Ford,  Volkswagen
data['Make'].value_counts()[:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

**4-What's the number of unique Audi car models in the dataset?**

In [21]:
data[data['Make'] == 'Audi']['Model'].value_counts().sum()

328

In [37]:
# 34 unique number
len(set(data[data['Make'] == 'Audi']['Model'].values))

34

**5-How many columns in the dataset have missing values?**

In [44]:
# 5 missing cols
data.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

**6-**

* Find the median value of "Engine Cylinders" column in the dataset.

* Next, calculate the most frequent value of the same "Engine Cylinders".

* Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.

* Now, calculate the median value of "Engine Cylinders" once again.


Hint: refer to existing `mode` and `median` functions to complete the task.

In [60]:
# the median
the_median_value = data['Engine Cylinders'].median()
the_median_value

6.0

In [74]:
# the most frequent
the_most_frequent = data['Engine Cylinders'].mode()[0]
the_most_frequent

4.0

In [75]:
# first, we show if it's have a missing values or not ... it's yes!
data['Engine Cylinders'].isna().sum()

30

In [76]:
# fill in missing values with the median
data['Engine Cylinders'] = data['Engine Cylinders'].fillna(the_most_frequent)

In [77]:
# check if already filled !
data['Engine Cylinders'].isna().sum()

0

In [78]:
# 5 missing cols
data.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders        0
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

**7-**

* Select all the "Lotus" cars from the dataset.

* Select only columns "Engine HP", "Engine Cylinders".

* Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).

* Get the underlying NumPy array. Let's call it X.

* Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.

* Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

* What's the value of the first element of w?
Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [87]:
data[data['Make'] == 'Lotus']

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
3912,Lotus,Elise,2009,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,43995
3913,Lotus,Elise,2009,premium unleaded (required),218.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,54990
3914,Lotus,Elise,2009,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,47250
3915,Lotus,Elise,2010,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,47250
3916,Lotus,Elise,2010,premium unleaded (required),218.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,54990
3917,Lotus,Elise,2011,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,51845
3918,Lotus,Elise,2011,premium unleaded (required),217.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,54990
3919,Lotus,Elise,2011,premium unleaded (required),217.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,57950
4216,Lotus,Esprit,2002,premium unleaded (required),350.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,21,14,613,89825
4217,Lotus,Esprit,2003,premium unleaded (required),350.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,21,14,613,90825
4218,Lotus,Esprit,2004,premium unleaded (required),350.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,21,14,613,93225
4257,Lotus,Evora 400,2017,premium unleaded (required),400.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,39,21,613,91900
4258,Lotus,Evora 400,2017,premium unleaded (required),400.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,39,21,613,91900
4259,Lotus,Evora,2011,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,27,18,613,64000
4260,Lotus,Evora,2011,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,65500
4261,Lotus,Evora,2013,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,66800
4262,Lotus,Evora,2013,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,77100
4263,Lotus,Evora,2013,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,78600
4264,Lotus,Evora,2013,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,68300
4265,Lotus,Evora,2014,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,78750
4266,Lotus,Evora,2014,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,68750
4267,Lotus,Evora,2014,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,79980
4268,Lotus,Evora,2014,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,69980
4292,Lotus,Exige,2009,premium unleaded (recommended),257.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,74995
4293,Lotus,Exige,2009,premium unleaded (recommended),240.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,65690
4294,Lotus,Exige,2010,premium unleaded (recommended),240.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,65690
4295,Lotus,Exige,2011,premium unleaded (recommended),240.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,65690
4296,Lotus,Exige,2011,premium unleaded (recommended),257.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,70750
4297,Lotus,Exige,2011,premium unleaded (recommended),257.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,74950

In [92]:
data[["Engine HP", "Engine Cylinders"]].drop_duplicates()

       Engine HP  Engine Cylinders
0          335.0               6.0
1          300.0               6.0
3          230.0               6.0
15         320.0               6.0
17         172.0               6.0
...          ...               ...
11640      197.0               5.0
11768      410.0               6.0
11792       97.0               4.0
11885      184.0               6.0
11903      394.0               8.0

[567 rows x 2 columns]